 # NOTE: update this with your service name
service: uploads

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
provider:
  variableSyntax: "\\${([^cognito*+][ :a-zA-Z0-9._,\\-\\/\\(\\)]+?)}" # ${cognito-identity.amazonaws.com:sub}をそのまま文字列として出力するようにする。
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::yukashita-image-uploads/original-files/${self:provider.stage}/*"
functions:
  auth:
    handler: auth.auth
    timeout : 5
    memorySize : 128
  hello:
    handler: test.hello
    events:
      - http:
          path: hello
          method: get
          authorizer: auth
      - http:
          path: hello
          method: options
    memorySize: 128
    response:
      headers:
        Content-Type: "'application/json'"
      template: $input.path('$')
    cors:
      origins:
        - '*'
      headers:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
      allowCredentials: false
  upload:
    handler: handler.upload
    events:
      - http:
          path: upload
          method: post
          authorizer: auth
      - http:
          path: upload
          method: options
    memorySize: 128
    response:
      headers:
        Content-Type: "'application/json'"
      template: $input.path('$')
    cors:
      origins:
        - '*'
      headers:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
      allowCredentials: false
resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "yukashita-image-uploads"
